DELETE FROM review_likes;
DELETE FROM reviews;
DELETE FROM likes;
DELETE FROM films_genre;
DELETE FROM film_director;
DELETE FROM films;
DELETE FROM friends;
DELETE FROM users;
DELETE FROM directors;

ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE films ALTER COLUMN id RESTART WITH 1;
ALTER TABLE directors ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reviews ALTER COLUMN id RESTART WITH 1;